- name: Add epel-release
  yum:
    name=epel-release
    state=present
  when: release == 5.6

- name: Enable remi-php56 repository
  yum:
    name={{ remi_rpms }}
    state=present
  when: release == 5.6

- name: Enable Remi repository
  ini_file:
    dest={{ remi_repo_file }}
    section={{ remi_section }}
    option=enabled
    value=1
  when: release == 5.6

- name: Install required packages
  yum:
    name={{ item }}
    state=present
  with_items: php_packages

- name: Install pecl packages
  shell: pecl install {{ item }}
  with_items: pecl_packages
  ignore_errors: yes

- name: Add corresponding config in php.d
  copy:
    dest=/etc/php.d/{{ item }}.ini
    content="extension={{ item }}.so"
    owner=root
    group=root
  with_items: pecl_packages
