- name: Add epel-release
  yum:
    name=epel-release
    state=present

- name: Install php rpm
  yum:
    name=http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state=present

- name: Edit /etc/yum.repos.d/remi.repo
  ini_file:
    dest=/etc/yum.repos.d/remi.repo
    section=remi-php56
    option=enabled
    value=1

- name: Install required packages
  yum:
    name={{ item }}
    state=present
  with_items: php_packages

- name: Install pecl packages
  shell: pecl install {{ item }}
  with_items: pecl_packages
  ignore_errors: yes

- name: Add corresponding config in php.d
  copy:
    dest=/etc/php.d/{{ item }}.ini
    content="extension={{ item }}.so"
    owner=root
    owner=root
  with_items: pecl_packages