---
#
# Setup REMI repo 
#

# Epel is a dependency
- name: Add epel-release
  yum:
    name=epel-release
    state=present

# Select remi repo depending on the CentOS version
- name: yum | Set remi repo var (rhel7)
  set_fact:
    remi_repo={{ remi_repo_el7 }}
  when: 
    ansible_distribution_major_version == '7'

- name: yum | Set remi repo var (rhel6)
  set_fact:
    remi_repo={{ remi_repo_el6 }}
  when: 
    ansible_distribution_major_version == '6'

- name: yum | Set remi repo var (rhel5)
  set_fact:
    remi_repo={{ remi_repo_el5 }}
  when: 
    ansible_distribution_major_version == '5'

# Install Remi Repo
- name: yum | Setup remi repo
  yum: 
    name={{ remi_repo }}
    state=present


#
# Activate PHP section depending on the release
#

# Select the php section
- name: yum | Set remi repo php section var
  set_fact:
    remi_section=remi-php55
  when: 
    release == '5.5'

- name: yum | Set remi repo php section var
  set_fact:
    remi_section=remi-php56
  when: 
    release == '5.6'

- name: yum | Set remi repo php section var
  set_fact:
    remi_section=remi-php70
  when:
    release == '7.0'

# Enable Section in remi.repo
- name: Enable Remi repository
  command: yum-config-manager --enable {{ remi_section }}


#
# Install PHP
#
- name: Install required packages
  yum:
    name={{ item }}
    state=present
  with_flattened: 
    - "{{ yum_php_packages }}"
    - "{{ php_packages }}"

# NOTE: pecl_packages could include versions like
#   acpu-4.0.10 --> pecl package/php module is acpu, version is 4.0.10
- name: Install pecl packages
  shell: 
    creates=/root/.pecl_{{ item | regex_replace('-(.*)','') }}
    yes | pecl install -a {{ item }} && touch /root/.pecl_{{ item | regex_replace('-(.*)','') }}
  with_items: pecl_packages
  ignore_errors: yes

- name: Add corresponding config in php.d
  copy:
    dest=/etc/php.d/{{ item | regex_replace('-(.*)','') }}.ini
    content="extension={{ item | regex_replace('-(.*)','') }}.so"
    owner=root
    group=root
  with_items: pecl_packages
