- name: Add epel-release
  yum:
    name=epel-release
    state=present

- name: Install php rpm
  yum:
    name=http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state=present

- name: Edit /etc/yum.repos.d/remi.repo
  ini_file:
    dest=/etc/yum.repos.d/remi.repo
    section=remi-php56
    option=enabled
    value=1

- name: Install required packages
  yum:
    name={{ item }}
    state=present
  with_items: default_php_packages

- name: Install pecl packages
  shell: pecl install {{ item }}
  with_items: default_pecl_packages
  ignore_errors: yes

- name: Add corresponding config in php.d with line extension={{ item }}.so
  ini_file:
    dest=/etc/php.d/{{ item }}.ini
    # section=PHP
    option=extension
    value={{ item }}.so