- name: Add epel-release
  yum:
    name=epel-release
    state=present

- name: Enable remi-php56 repository
  yum:
    name={{ remi_rpms }}
    state=present

- name: Edit /etc/yum.repos.d/remi.repo
  ini_file:
    dest={{ remi_repo_file }}
    section={{ remi_section }}
    option=enabled
    value=1

- name: Install required packages
  yum:
    name={{ item }}
    state=present
  with_items: php_packages

- name: Install pecl packages
  shell: pecl install {{ item }}
  with_items: pecl_packages
  ignore_errors: yes

- name: Add corresponding config in php.d
  copy:
    dest=/etc/php.d/{{ item }}.ini
    content="extension={{ item }}.so"
    owner=root
    owner=root
  with_items: pecl_packages

- name: Install composer.phar
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  when: install_composer
