---
#
# Custom versions of PHP comes from PPA
#
# Select the right PPA depending on the expected release
- name: apt | Set PPA repo var (php 5.4)
  set_fact:
    ppa_php={{ ppa_php_54 }}
  when: 
    release == '5.4'

- name: apt | Set PPA repo var (php 5.5)
  set_fact:
    ppa_php={{ ppa_php_55 }}
  when: 
    release == '5.5'

- name: apt | Set PPA repo var (php 5.6)
  set_fact:
    ppa_php={{ ppa_php_56 }}
  when: 
    release == '5.6'

# Add the PPA repository to the APT sources
- name: Ensure PHP repo is installed from PPA
  apt_repository:
    repo='{{ ppa_php }}'
    state=present

# Install the required packages
- name: Install required packages
  apt:
    name={{ item }}
    state=present
    update_cache=yes
  with_flattened: 
    - "{{ apt_php_packages }}"
    - "{{ php_packages }}"

- name: Install pecl packages
  shell: pecl install {{ item }}
  with_items: pecl_packages
  ignore_errors: yes

- name: Add PHP PECL extension config in mods-available
  copy:
    dest=/etc/php5/mods-available/{{ item }}.ini
    content="extension={{ item }}.so"
    owner=root
    group=root
  with_items: pecl_packages

- name: Enable PHP PECL extensions
  shell:
    creates=/etc/php5/cli/conf.d/20-{{ item }}.ini
    php5enmod -s ALL {{ item }}
  with_items: pecl_packages
