---
#
# Custom versions of PHP comes from PPA
#
# Select the right PPA depending on the expected release
- name: apt | Set PPA repo var (php 5.4)
  set_fact:
    ppa_php={{ ppa_php_54 }}
  when:
    release == '5.4'

- name: apt | Set PPA repo var (php 5.5)
  set_fact:
    ppa_php={{ ppa_php_55 }}
  when:
    release == '5.5'

- name: apt | Set PPA repo var (php 5.6)
  set_fact:
    ppa_php={{ ppa_php_56 }}
  when:
    release == '5.6'

- name: apt | Set PPA repo var (php 7.0)
  set_fact:
    ppa_php={{ ppa_php_70 }}
  when:
    release == '7.0'

- name: apt | Set PPA repo var (php 7.1)
  set_fact:
    ppa_php={{ ppa_php_70 }}
  when:
    release == '7.1'

# Add the PPA repository to the APT sources
- name: Ensure PHP repo is installed from PPA
  apt_repository:
    repo='{{ ppa_php }}'
    state=present

# Install the required packages
- name: Install required packages
  apt:
    name={{ item }}
    state=present
    update_cache=yes
  with_flattened: 
    - "{{ apt_php_packages }}"
    - "{{ php_packages }}"

# NOTE: pecl_packages could include versions like
#   acpu-4.0.10 --> pecl package/php module is acpu, version is 4.0.10
- name: Install pecl packages
  shell: 
    creates=/root/.pecl_{{ item | regex_replace('-(.*)','') }}
    yes | pecl install -a {{ item }} && touch /root/.pecl_{{ item | regex_replace('-(.*)','') }}
  with_items: pecl_packages
  ignore_errors: yes

- name: Add PHP PECL extension config in mods-available
  copy:
    dest=/etc/php5/mods-available/{{ item | regex_replace('-(.*)','') }}.ini
    content="extension={{ item | regex_replace('-(.*)','') }}.so"
    owner=root
    group=root
  with_items: pecl_packages

- name: Enable PHP PECL extensions
  shell:
    creates=/etc/php5/cli/conf.d/20-{{ item | regex_replace('-(.*)','') }}.ini
    php5enmod -s ALL {{ item | regex_replace('-(.*)','') }}
  with_items: pecl_packages
