---
- name: Install in Debian.
  include: debian.yml
  when: ansible_os_family == 'Debian'

- name: Install in RedHat / CentOS.
  include: centos.yml
  when: ansible_os_family == 'RedHat'

- name: install composer
  shell: 
    chdir=/usr/local/bin
    creates=/usr/local/bin/composer
    curl -sS https://getcomposer.org/installer | php -d allow_url_fopen=On -- --filename=composer
  when: install_composer
